### ISSUE TITLE
Example data to xdmod team

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#33]
I have corrected all of the issues that I have been able to spot in terms of getting the data from openstack to be processed by xdmod.  The dates look ok, the event times don't coincide, the sequence seems ok.

At this point, either there are the following possibilities:

1) there is something wrong with the data
2) You have to process more event than just create and exists
3) there is something incorrect in my configuration
4) I am looking at the wrong part of the interface

To resolve this, I will pass the xdmod team a short example of 2 or three VMs and the debug shredder/ingestation file output and ask them why I am not able to see any data in the interface.

**Comment by joachimweyl** [comment]
Blocked on awaiting XDMoD reply.

**Comment by joachimweyl** [comment]
@rob-baron this is the data that is dependent on Harvard systems coming up or if not using `ocp-staging` right?

**Comment by joachimweyl** [comment]
@rob-baron is the ticket with XDMoD viewable to others or does it require a log/pass? If it is viewable to others can you share the link please?

**Comment by joachimweyl** [comment]
Gregary Dean piece of email
"I think the combination of the first xdmod-ingestor run dropping the DB connection and stopping after data had been ingested but not aggregated, and not specifying the --last-modified-start-date flag when xdmod-ingestor ran a second time caused the events to not be aggregated. Since the events were not aggregated no data would show in the interface. In this instance, the fix is to run the xmdod-ingestor command with the --last-modified-start-date flag whose time is before the first run of xdmod-ingestor. Something like the following command would work, xdmod-ingestor --last-modified-start-date "2022-05-31 12:30:00". If you've already tried that and data still doesn't show up let me know."

**Comment by joachimweyl** [comment]
@rob-baron did Greg's suggestions bear any fruit?

**Comment by rob-baron** [comment]
His explanation clarified things,

1) xdmod-ingestor failed due to the database dropping the connection, but after the last run date was set.
2) subsequent runs of xdmod-ingestor only aggregated after that time.

We need to use the --last-modified-start-date to force data to be either aggregated or re-aggregated  when xdmod-ingestor fails.

I set things up in staging (where we don't seem to have the issue of the database dropping the connection), and was able to process the data.  So we get data in the interface.

Still have problems, but different problems (and yes, staging seems more stable than the NERC).

**Comment by rob-baron** [comment]
So I think we can close this (and open other issues).
